# This workflow builds and uploads signed .apk packages for pull requests and pushes to master.
# This uses `pull_request_target` event to have access to secrets for pull requests from forks.
name: Package

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - master

jobs:

  #----------------------------------------------------------------------------
  # Cache LFS: Checkout LFS data and update the cache to limit LFS bandwidth
  #----------------------------------------------------------------------------
  cache_lfs:
    runs-on: ubuntu-22.04
    name: Update LFS data cache
    outputs:
      lfs_sha: ${{ steps.lfs_sha_recover.outputs.lfs_sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "source"
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 1
          lfs: false

      - name: Cache LFS Data
        id: lfs_sha_recover
        uses: f3d-app/lfs-data-cache-action@v2
        with:
          cache_postfix: cache-0

  #----------------------------------------------------------------------------
  # Build and upload .apk packages
  #----------------------------------------------------------------------------
  build:
    needs: [cache_lfs]

    name: Build and upload signed APKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "source"
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0
          lfs: false

      - name: Recover LFS Data
        uses: f3d-app/lfs-data-cache-action@v2
        with:
            type: "consumer"
            lfs_sha: ${{ needs.cache_lfs.outputs.lfs_sha }}
            cache_postfix: cache-0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Decode keystore
        working-directory: ${{github.workspace}}/source
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > f3d/f3d-android-key.jks

      - name: Build APKs
        working-directory: ${{github.workspace}}/source
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        run: ./gradlew assembleRelease --no-configuration-cache

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: ./source/f3d/build/outputs/apk/release/*.apk
